#!/bin/bash
#
# ========* upload2gdrive *==========
#  This tool recursively uploads the 
#  input directory to Google Drive.
# ===================================
#
# ---- INITIALIZE ----
# define a few more parameters
do_compress=${2:-1}
# check that param and lib files can be sourced, and source them.
for resources in "./gdprm.sh" "./gdlib.sh"; do 
  if [ ! -f $resources ]; then 
    echo "ERROR: $resource not found here $PWD"; exit
  else 
    source $resources
  fi
done
if [ $# -lt 1 ]; then 
  echo "Provide the directory name that you want to upload to gdrive"; exit
fi
#
# ---- RUN ----
# upload recursively
function main() { jobid="$RANDOM"; upload_recursive "$1 $jobid $do_compress"; }
main "$1"
# the end!
